### ISSUE TITLE
Cookbook is not available in Supermarket

### ISSUE THREAD

**Issue by shanethehat** [continuent/continuent-chef-tungsten#26]
This cookbook is not currently available in Chef Supermarket. It can be added to Supermarket using knife: https://docs.chef.io/knife_cookbook_site.html#share

The benefit of using Supermarket for this cookbook is that the Berkshelf API will be able manage it more effectively, which will reduce duplication by making management of chained dependencies automatic.

**Comment by jeffmace** [comment]
The cookbook is now posted to https://supermarket.chef.io/cookbooks/tungsten.
